# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'CityWalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # 高德地图3D SDK
  pod 'AMap3DMap'
  
  # 高德定位SDK
  pod 'AMapLocation'

end
